/*
 * File: app/view/dangnhap.js
 * Date: Sat Mar 17 2018 15:11:03 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.dangnhap', {
    extend: 'Ext.Container',
    alias: 'widget.dangnhap',

    requires: [
        'LoginApp.view.dangnhapViewModel',
        'Ext.Container',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.Label'
    ],

    viewModel: {
        type: 'dangnhap'
    },
    style: '\'background-image:url("images/Nam 1.png"); background-size:cover;',
    displayed: false,
    html: '',
    layout: 'fit',
    masked: false,

    items: [
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'container',
                    height: 100,
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    docked: 'top',
                    margin: '70 70 0 70'
                },
                {
                    xtype: 'container',
                    height: 46,
                    style: 'tex-align:center;',
                    width: '',
                    docked: 'top',
                    margin: '10% 50% 0 50%',
                    autoSize: false,
                    layout: 'center',
                    items: [
                        {
                            xtype: 'textfield',
                            border: true,
                            cls: 'textField',
                            height: 30,
                            name: '',
                            style: 'border-radius:100px;border:none;text-align:center;',
                            toFrontOnShow: false,
                            width: '100%',
                            docked: 'bottom',
                            html: '',
                            margin: '',
                            scrollable: false,
                            label: '',
                            labelAlign: 'bottom',
                            required: true,
                            clearable: false,
                            placeholder: 'Nhập số điện thoại',
                            triggers: {
                                foo: {
                                    side: 'left',
                                    cls: 'fa-trigger my-mobile-trigger',
                                    
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    docked: 'top',
                    margin: '20%',
                    scrollable: false,
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            toggleHandler: function(button, pressed) {
                                this.up('main').setActiveItem(1);
                            },
                            cls: 'btn',
                            height: 30,
                            style: '',
                            ui: 'dangnhap',
                            width: 130,
                            margin: '',
                            text: 'Đăng nhập'
                        },
                        {
                            xtype: 'label',
                            defaultListenerScope: true,
                            itemId: 'mylabel',
                            style: 'text-align:center;',
                            docked: 'bottom',
                            html: '<a class="link" href="">Đăng Ký</a>',
                            margin: '20%',
                            listeners: {
                                tap: 'onButtonTap'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onButtonTap: function(button, e, eOpts) {
        alert('Hung dep zai');
    }

});