/*
 * File: app/view/dat_matkhau.js
 * Date: Sat Mar 17 2018 15:11:03 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.dat_matkhau', {
    extend: 'Ext.Container',
    alias: 'widget.dat_matkhau',

    requires: [
        'LoginApp.view.hungViewModel2',
        'Ext.Container',
        'Ext.field.Text',
        'Ext.Label',
        'Ext.Button'
    ],

    viewModel: {
        type: 'dat_matkhau'
    },
    style: '\'background-image:url("images/Nam 1.png"); background-size:cover;',
    displayed: false,
    html: '',
    layout: 'fit',
    masked: false,

    items: [
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'container',
                    height: 201,
                    style: 'tex-align:center;',
                    width: '',
                    docked: 'top',
                    margin: '60% 50% 0 50%',
                    autoSize: false,
                    layout: 'center',
                    items: [
                        {
                            xtype: 'textfield',
                            border: false,
                            cls: 'textField',
                            height: 30,
                            name: '',
                            style: '',
                            toFrontOnShow: false,
                            width: '100%',
                            docked: 'bottom',
                            html: '',
                            margin: '',
                            scrollable: false,
                            inline: true,
                            label: '',
                            labelAlign: 'bottom',
                            required: true,
                            inputType: 'password',
                            clearable: false,
                            placeholder: '****',
                            textAlign: 'center'
                        },
                        {
                            xtype: 'label',
                            style: 'text-align:center;',
                            docked: 'top',
                            html: '<h4 class="title-xn">ĐĂNG NHẬP THÀNH CÔNG</h4><p class="content-tb">Chào mừng bạn đến với Empire City.</p>  '
                        },
                        {
                            xtype: 'label',
                            height: 44,
                            style: 'text-align:center;',
                            docked: 'bottom',
                            html: '<p class="content-tb">Thiết lập mật khẩu ứng dụng</p>'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    docked: 'top',
                    margin: '20%',
                    scrollable: false,
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            toggleHandler: function(button, pressed) {
                                this.up('main').setActiveItem(1);
                            },
                            height: 30,
                            style: 'border-radius:20px;',
                            userCls: 'btn',
                            width: 140,
                            margin: '',
                            text: 'Đặt mật khẩu'
                        },
                        {
                            xtype: 'label',
                            defaultListenerScope: true,
                            itemId: 'mylabel',
                            style: 'text-align:center;font-size:9px;',
                            docked: 'bottom',
                            html: '<span>Bỏ qua thiết lập mật khẩu, <b>tiếp tục sử dung</b></span>',
                            margin: '20%',
                            listeners: {
                                tap: 'onButtonTap'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onButtonTap: function(button, e, eOpts) {
        alert('Hung dep zai');
    }

});