/*
 * File: app/view/Event.js
 * Date: Thu Mar 15 2018 10:53:51 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('adc.view.Event', {
    extend: 'Ext.Container',
    alias: 'widget.event',

    requires: [
        'Ext.Container',
        'Ext.Button',
        'Ext.Label'
    ],

    height: '100%',
    padding: '',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '10%',
            width: '100%',
            centered: true,
            docked: 'top',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    width: 450,
                    html: '',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'menu-button',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-user-circle',
                            text: ''
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '85%',
            margin: 5,
            scrollable: false,
            layout: 'card',
            items: [
                {
                    xtype: 'container',
                    scrollable: {
                        direction: 'both',
                        indicators: {
                            x: {
                                autoHide: false
                            }
                        }
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: '8%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'title-container',
                                    height: '10%',
                                    html: 'Sự kiện',
                                    margin: ''
                                },
                                {
                                    xtype: 'container',
                                    docked: 'top'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '50%',
                            margin: 5,
                            items: [
                                {
                                    xtype: 'container',
                                    height: '50%',
                                    style: 'background-color:pink;',
                                    docked: 'top',
                                    zIndex: 99
                                },
                                {
                                    xtype: 'container',
                                    height: '35%',
                                    docked: 'top',
                                    zIndex: 99,
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'container',
                                            width: '20%',
                                            layout: 'center',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    style: 'font-size: 15px;text-align:center;',
                                                    html: 'Tháng 7 08'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            width: '80%',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: '50%',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            style: 'font-size: 17px;',
                                                            html: 'Sự kiện 1'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    height: '25%',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            html: '<i class="fa fa-calendar"></i>1-1-2018 8:00'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    height: '25%',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            html: '<i class="fa fa-map-marker"></i> Địa chỉ 88,p88,q88,tp.hcm'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: '15%',
                                    docked: 'top',
                                    zIndex: 99,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'container',
                                            margin: '1 1 1 5',
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    ui: 'raised',
                                                    icon: 'true',
                                                    iconCls: 'x-fa fa-check',
                                                    text: 'Tham gia'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            margin: '1 5 1 1',
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    ui: 'raised',
                                                    icon: 'true',
                                                    iconCls: 'x-fa fa-times-circle',
                                                    text: 'Không tham gia'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '50%',
                            margin: 5,
                            items: [
                                {
                                    xtype: 'container',
                                    height: '50%',
                                    style: 'background-color:green;',
                                    docked: 'top',
                                    zIndex: 99
                                },
                                {
                                    xtype: 'container',
                                    height: '35%',
                                    docked: 'top',
                                    zIndex: 99,
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'container',
                                            width: '20%',
                                            layout: 'center',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    style: 'font-size: 15px;text-align:center;',
                                                    html: 'Tháng 7 08'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            width: '80%',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: '50%',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            style: 'font-size: 17px;',
                                                            html: 'Sự kiện 2'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    height: '25%',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            html: '<i class="fa fa-hourglass"></i>1-1-2018 8:00'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    height: '25%',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            html: '<i class="fa fa-calendar"></i> Địa chỉ 88,p88,q88,tp.hcm'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: '15%',
                                    docked: 'top',
                                    zIndex: 99,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'container',
                                            margin: '1 1 1 5',
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    ui: 'raised',
                                                    icon: 'true',
                                                    iconCls: 'x-fa fa-check',
                                                    text: 'Tham gia'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            margin: '1 5 1 1',
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    ui: 'raised',
                                                    icon: 'true',
                                                    iconCls: 'x-fa fa-times-circle',
                                                    text: 'Không tham gia'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '15%',
            style: 'background-color: #2a8daf;',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-home',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            height: 10,
                            html: 'Trang chủ'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-file',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Tin tức'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-star',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Sự kiện'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-gift',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Đặc quyền'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-credit-card',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Thanh toán'
                        }
                    ]
                }
            ]
        }
    ]

});