/*
 * File: app/view/hung.js
 * Date: Sat Mar 17 2018 13:45:53 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.hung', {
    extend: 'Ext.Container',
    alias: 'widget.hung',

    requires: [
        'LoginApp.view.hungViewModel14',
        'Ext.Container'
    ],

    viewModel: {
        type: 'hung'
    },
    style: '\'background-image:url("images/Nam 2.png"); background-size:cover;',
    displayed: false,
    html: '',
    layout: 'fit',
    masked: false,

    items: [
        {
            xtype: 'container',
            width: 400,
            layout: 'fit'
        }
    ]

});