/*
 * File: app/view/Menu.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmpriteCity.view.Menu', {
    extend: 'Ext.Container',
    alias: 'widget.menu',

    requires: [
        'EmpriteCity.view.LoginPanelViewModel1',
        'Ext.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.carousel.Carousel',
        'Ext.Img',
        'Ext.Label'
    ],

    viewModel: {
        type: 'menu'
    },
    padding: '',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '8%',
            width: '100%',
            centered: true,
            docked: 'top',
            layout: 'fit',
            items: [
                {
                    xtype: 'container'
                },
                {
                    xtype: 'container',
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    width: 450,
                    html: '',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    width: '50%',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            border: true,
                            hidden: false,
                            width: '40%'
                        },
                        {
                            xtype: 'container',
                            width: '60%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 30,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 30,
                                    arrow: false,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-user-circle',
                                    text: '',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '32%',
            style: 'background: url(images/city.png);background-position: center;background-size:cover;',
            width: '100%',
            centered: true,
            docked: 'top',
            maxHeight: '',
            minHeight: '',
            items: [
                {
                    xtype: 'carousel',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'container',
                            style: 'background: url(images/city.png);background-position: center;background-size:cover;'
                        },
                        {
                            xtype: 'image'
                        },
                        {
                            xtype: 'image'
                        },
                        {
                            xtype: 'image'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '60%',
            style: 'background-color: #2a8daf;',
            width: '100%',
            centered: true,
            docked: 'top',
            minHeight: '',
            minWidth: '',
            padding: 10,
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    height: '33%',
                    width: '100%',
                    layout: 'float',
                    items: [
                        {
                            xtype: 'container',
                            height: '100%',
                            width: '50%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'container',
                                    width: 79,
                                    margin: '',
                                    layout: 'float',
                                    items: [
                                        {
                                            xtype: 'container',
                                            width: 79,
                                            margin: '0 0 0 10%',
                                            layout: 'float',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    cls: 'menu-button',
                                                    height: 60,
                                                    style: 'border-radius: 50%;',
                                                    ui: 'menu-button',
                                                    width: 60,
                                                    icon: 'true',
                                                    iconCls: 'x-fa fa-volume-up',
                                                    text: ''
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'menu-label-text',
                                                    height: 17,
                                                    style: 'border-radius: 50%; background-color: red; text-align:center;',
                                                    width: 17,
                                                    html: '2',
                                                    margin: '5 0 45 -15'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'label',
                                    cls: 'menu-label-text',
                                    html: 'Thông báo'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '100%',
                            width: '50%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    cls: 'menu-button',
                                    height: 60,
                                    style: 'font-size: 50px;',
                                    ui: 'menu-button',
                                    userCls: 'menu-button',
                                    width: 60,
                                    weight: 200,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-file-text-o',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    cls: 'menu-label-text',
                                    html: 'Tin tức'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '33%',
                    width: '100%',
                    layout: 'float',
                    items: [
                        {
                            xtype: 'container',
                            height: '100%',
                            width: '50%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 60,
                                    style: 'border-radius: 50%;',
                                    ui: 'menu-button',
                                    width: 60,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-star-o',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    cls: 'menu-label-text',
                                    html: 'Sự kiện'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '100%',
                            width: '50%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    cls: 'menu-button',
                                    height: 60,
                                    style: 'border-radius: 50%;',
                                    ui: 'menu-button',
                                    userCls: 'menu-button',
                                    width: 60,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-gift',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    cls: 'menu-label-text',
                                    html: 'Đặc quyền'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '34%',
                    layout: 'float',
                    items: [
                        {
                            xtype: 'container',
                            height: '100%',
                            width: '50%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 60,
                                    style: 'border-radius: 50%;',
                                    ui: 'menu-button',
                                    width: 60,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-credit-card',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    cls: 'menu-label-text',
                                    html: 'Thanh toán'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '100%',
                            width: '50%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 60,
                                    style: 'border-radius: 50%;',
                                    ui: 'menu-button',
                                    width: 60,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-cog',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    cls: 'menu-label-text',
                                    html: 'Cài đặt'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});