/*
 * File: app/view/MyContainer4.js
 * Date: Thu Mar 15 2018 16:55:41 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('adc.view.MyContainer4', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer4',

    requires: [
        'adc.view.MyContainer4ViewModel',
        'Ext.Container',
        'Ext.Img',
        'Ext.Button'
    ],

    viewModel: {
        type: 'mycontainer4'
    },

    items: [
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'image',
                    height: 201,
                    src: 'Nam%201.png'
                },
                {
                    xtype: 'container',
                    height: 85,
                    html: '<div class="test-a">asdasdasdsdfsdgsgdfvsdstrehgfxdhrtdjhdfxgrxdasdas</div>',
                    margin: '-50 0 0 0',
                    zIndex: 10
                }
            ]
        },
        {
            xtype: 'button',
            ui: 'confirm round',
            text: 'MyButton1'
        }
    ]

});