/*
 * File: app/view/MyContainer5.js
 * Date: Sat Mar 17 2018 13:23:24 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.MyContainer5', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer5',

    requires: [
        'LoginApp.view.MyContainer5ViewModel',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Button'
    ],

    viewModel: {
        type: 'mycontainer5'
    },
    border: false,
    cls: 'my_list',
    layout: 'box',

    items: [
        {
            xtype: 'container',
            docked: 'top',
            margin: '',
            layout: 'center',
            items: [
                {
                    xtype: 'container',
                    docked: 'top',
                    html: '<div class="title">Hỗ trợ</div>',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    height: 33,
                    docked: 'top',
                    html: '<p class="tt">Những câu hỏi thường gặp</p>',
                    layout: 'float'
                },
                {
                    xtype: 'list',
                    cls: 'tpl-o6oa9nk3',
                    height: 347,
                    shadow: false,
                    width: '',
                    axisLock: false,
                    data: [
                        {
                            title: 'Thủ tục thay đổi thông tin hợp đồng'
                        },
                        {
                            title: 'Thanh toán quá hạn'
                        },
                        {
                            title: 'Chứng từ thanh toán'
                        },
                        {
                            title: 'Thủ tục chuyển quyền sử dụng BĐS'
                        },
                        {
                            title: 'Thủ tục thuế'
                        },
                        {
                            title: 'Phạm vi hợp đồng cọc'
                        },
                        {
                            title: 'Quyền sỡ hữu của người nước ngoài'
                        },
                        {
                            title: 'Mua bán - đã thế chấp'
                        }
                    ],
                    displayed: false,
                    docked: 'top',
                    draggable: false,
                    hideOnMaskTap: false,
                    margin: '',
                    padding: 10,
                    inline: false,
                    itemTpl: [
                        '<div class="title-ht">{title}</div><div class="icon-ht"><i class="fa fa-angle-right btn-ht"></i></div>'
                    ],
                    grouped: true,
                    rowLines: false
                }
            ]
        },
        {
            xtype: 'container'
        },
        {
            xtype: 'container',
            docked: 'top',
            margin: '20 0 0 0',
            layout: 'center',
            items: [
                {
                    xtype: 'button',
                    cls: 'btn',
                    style: 'text-transform :none;',
                    ui: 'dangnhap',
                    width: 179,
                    text: 'Gửi câu hỏi của bạn'
                }
            ]
        }
    ]

});