/*
 * File: app/view/MyContainer8.js
 * Date: Fri Mar 16 2018 11:43:10 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('adc.view.MyContainer8', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer8',

    requires: [
        'adc.view.MyContainer8ViewModel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'mycontainer8'
    },
    docked: 'top',

    items: [
        {
            xtype: 'list',
            data: [
                {
                    image: 'Nam 1.png',
                    title: 'sadasdasd',
                    content: 'dsadasdasvdsfafasfasfas'
                }
            ],
            itemTpl: [
                '<img src="{image}" width="300" height="200"><div>List Item {title}</div><div>{content}</div>'
            ]
        }
    ]

});