/*
 * File: app/view/News.js
 * Date: Sat Mar 17 2018 14:05:47 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.News', {
    extend: 'Ext.Container',
    alias: 'widget.news',

    requires: [
        'LoginApp.view.LoginPanelViewModel3',
        'Ext.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.Label',
        'Ext.Img',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'news'
    },
    height: '100%',
    padding: '',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '8%',
            width: '100%',
            centered: true,
            docked: 'top',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    width: 450,
                    html: '',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    width: '50%',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            width: '40%'
                        },
                        {
                            xtype: 'container',
                            width: '60%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 40,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    arrow: false,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-user-circle',
                                    text: '',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-user',
                                                text: 'Tài khoản'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-qrcode',
                                                text: 'QR Code'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-question-circle-o',
                                                text: 'Hỗ trợ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-cog',
                                                text: 'Cài đặt'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-headphones',
                                                text: 'Liên hệ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-sign-out',
                                                text: 'Đăng xuất'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '88%',
            layout: 'card',
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'container',
                            height: '6%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'title-container',
                                    height: '10%',
                                    html: 'Tin tức',
                                    margin: ''
                                },
                                {
                                    xtype: 'container',
                                    docked: 'top'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '40%',
                            html: '',
                            items: [
                                {
                                    xtype: 'container',
                                    height: '100%',
                                    width: '100%',
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: '100%',
                                            style: 'background-size:cover;',
                                            src: 'https://i.ytimg.com/vi/-PsSfuAm-ws/maxresdefault.jpg'
                                        },
                                        {
                                            xtype: 'container',
                                            height: '50%',
                                            style: 'background-color:rgba(0,0,0,0.3);',
                                            html: '<div class="news-banner-title">Tin tức 1</div><div class="news-banner-time">2 giờ trước</div>',
                                            margin: '-60% 0 0 0',
                                            padding: 10
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '50%',
                            margin: 5,
                            items: [
                                {
                                    xtype: 'list',
                                    height: 215,
                                    data: [
                                        {
                                            title: 'Emprite City Win Gold',
                                            picture: {
                                                large: 'https://randomuser.me/api/portraits/women/63.jpg',
                                                medium: 'https://randomuser.me/api/portraits/med/women/63.jpg',
                                                thumbnail: 'https://randomuser.me/api/portraits/thumb/women/63.jpg'
                                            },
                                            shortdesc: [
                                                'this is description for this news, this is description for this news'
                                            ],
                                            time: [
                                                '1/1/2018'
                                            ],
                                            
                                        },
                                        {
                                            title: 'Running For Your life',
                                            picture: {
                                                large: 'https://randomuser.me/api/portraits/women/4.jpg',
                                                medium: 'https://randomuser.me/api/portraits/med/women/4.jpg',
                                                thumbnail: 'https://randomuser.me/api/portraits/thumb/women/4.jpg'
                                            },
                                            shortdesc: [
                                                'this is description for this news, this is description for this news'
                                            ],
                                            time: [
                                                '1/1/2018'
                                            ],
                                            
                                        },
                                        
                                    ],
                                    itemTpl: [
                                        '<div class="list-item-dev">',
                                        '    <div class="list-header">',
                                        '        <img class="list-item-image" src="{picture.medium}"/> ',
                                        '    </div>',
                                        '    <div class="list-item-details">',
                                        '        <div class="list-item-name">{title}</div> ',
                                        '        <tpl for="shortdesc"> ',
                                        '            <div class="list-item-skill-tag">{.}</div> ',
                                        '        </tpl> ',
                                        '        <tpl for="time"> ',
                                        '            <div class="list-item-skill-tag">{.}</div> ',
                                        '        </tpl>',
                                        '    </div> ',
                                        '</div>'
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '12%',
            style: 'background-color: #2a8daf;',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-home',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Trang chủ'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-file-text-o',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Tin tức'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-star-o',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Sự kiện'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-gift',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Đặc quyền'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-credit-card',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Thanh toán'
                        }
                    ]
                }
            ]
        }
    ]

});