/*
 * File: app/view/phan_hoi.js
 * Date: Mon Mar 19 2018 16:09:56 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.phan_hoi', {
    extend: 'Ext.Container',
    alias: 'widget.phan_hoi',

    requires: [
        'LoginApp.view.LoginPanelViewModel11',
        'Ext.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.Label',
        'Ext.field.Select',
        'Ext.field.TextArea'
    ],

    viewModel: {
        type: 'phan_hoi'
    },
    height: '100%',
    data: {
        title: 'Ưu đãi giảm giá 20% tại Le Mendendline'
    },
    padding: '',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '8%',
            width: '100%',
            centered: true,
            docked: 'top',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    width: '33%',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 40,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-long-arrow-left',
                                    text: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    width: '33%',
                    html: '',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    width: '33%',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            width: '40%'
                        },
                        {
                            xtype: 'container',
                            width: '60%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 40,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    arrow: false,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-user-circle',
                                    text: '',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-user',
                                                text: 'Tài khoản'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-qrcode',
                                                text: 'QR Code'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-question-circle-o',
                                                text: 'Hỗ trợ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-cog',
                                                text: 'Cài đặt'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-headphones',
                                                text: 'Liên hệ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-sign-out',
                                                text: 'Đăng xuất'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '88%',
            layout: 'card',
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'container',
                            height: '8%',
                            style: 'border-bottom:1px solid #b8cfff;',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'title-container',
                                    height: '10%',
                                    html: 'Gửi phản hồi',
                                    margin: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: 20,
                            items: [
                                {
                                    xtype: 'selectfield',
                                    border: true,
                                    height: 33,
                                    style: 'border: 1px solid #ddd',
                                    toFrontOnShow: false,
                                    options: [
                                        {
                                            text: 'Thanh toán',
                                            value: '1'
                                        },
                                        {
                                            text: 'Event',
                                            value: '2'
                                        },
                                        {
                                            text: 'Khác',
                                            value: '3'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    border: true,
                                    style: 'border : 1px solid #ddd'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '12%',
            style: 'background-color: #2a8daf;',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-home',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Trang chủ'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-file',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Tin tức'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-star',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Sự kiện'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-gift',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Đặc quyền'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-credit-card',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Thanh toán'
                        }
                    ]
                }
            ]
        }
    ]

});