/*
 * File: app/view/QR_code.js
 * Date: Mon Mar 19 2018 16:02:34 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.QR_code', {
    extend: 'Ext.Container',
    alias: 'widget.QR_code',

    requires: [
        'LoginApp.view.LoginPanelViewModel14',
        'Ext.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.Label',
        'Ext.Img'
    ],

    viewModel: {
        type: 'qr_code'
    },
    disabled: true,
    height: '100%',
    data: {
        title: 'Ưu đãi giảm giá 20% tại Le Mendendline'
    },
    displayed: true,
    padding: '',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '8%',
            width: '100%',
            centered: true,
            docked: 'top',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    width: '33%',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 40,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-long-arrow-left',
                                    text: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    width: '33%',
                    html: '',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    width: '33%',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            width: '40%'
                        },
                        {
                            xtype: 'container',
                            width: '60%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 40,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    arrow: false,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-user-circle',
                                    text: '',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-user',
                                                text: 'Tài khoản'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-qrcode',
                                                text: 'QR Code'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-question-circle-o',
                                                text: 'Hỗ trợ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-cog',
                                                text: 'Cài đặt'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-headphones',
                                                text: 'Liên hệ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-sign-out',
                                                text: 'Đăng xuất'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '88%',
            layout: 'card',
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'container',
                            height: '8%',
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'title-container',
                                    height: '10%',
                                    html: 'Cập nhật tài khoản',
                                    margin: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '100%',
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'container',
                                    height: 250,
                                    style: 'background-size:cover;',
                                    width: 250,
                                    layout: 'center',
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: 201,
                                            width: 201,
                                            src: 'images/qrcode.png'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '12%',
            style: 'background-color: #2a8daf;',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-home',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Trang chủ'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-file',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Tin tức'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-star',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Sự kiện'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-gift',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Đặc quyền'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-credit-card',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Thanh toán'
                        }
                    ]
                }
            ]
        }
    ]

});