/*
 * File: app/view/Support.js
 * Date: Mon Mar 19 2018 16:26:00 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.Support', {
    extend: 'Ext.Container',
    alias: 'widget.support',

    requires: [
        'Ext.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Label'
    ],

    height: '100%',
    padding: '',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '8%',
            width: '100%',
            centered: true,
            docked: 'top',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    width: 450,
                    html: '',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    width: '50%',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            width: '40%'
                        },
                        {
                            xtype: 'container',
                            width: '60%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 30,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 30,
                                    arrow: false,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-user-circle',
                                    text: '',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-user',
                                                text: 'Tài khoản'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-qrcode',
                                                text: 'QR Code'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-question-circle-o',
                                                text: 'Hỗ trợ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-cog',
                                                text: 'Cài đặt'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-headphones',
                                                text: 'Liên hệ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-sign-out',
                                                text: 'Đăng xuất'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '88%',
            margin: '0 5 0 5',
            layout: 'card',
            items: [
                {
                    xtype: 'container',
                    scrollable: false,
                    items: [
                        {
                            xtype: 'container',
                            border: false,
                            cls: 'my_list',
                            layout: 'box',
                            items: [
                                {
                                    xtype: 'container',
                                    docked: 'top',
                                    margin: '',
                                    layout: 'center',
                                    items: [
                                        {
                                            xtype: 'container',
                                            docked: 'top',
                                            html: '<div class="title">Hỗ trợ</div>',
                                            layout: 'center'
                                        },
                                        {
                                            xtype: 'container',
                                            height: 33,
                                            docked: 'top',
                                            html: '<p class="tt">Những câu hỏi thường gặp</p>',
                                            layout: 'float'
                                        },
                                        {
                                            xtype: 'list',
                                            cls: 'tpl-o6oa9nk3',
                                            height: 347,
                                            shadow: false,
                                            width: '',
                                            axisLock: false,
                                            data: [
                                                {
                                                    title: 'Thủ tục thay đổi thông tin hợp đồng'
                                                },
                                                {
                                                    title: 'Thanh toán quá hạn'
                                                },
                                                {
                                                    title: 'Chứng từ thanh toán'
                                                },
                                                {
                                                    title: 'Thủ tục chuyển quyền sử dụng BĐS'
                                                },
                                                {
                                                    title: 'Thủ tục thuế'
                                                },
                                                {
                                                    title: 'Phạm vi hợp đồng cọc'
                                                },
                                                {
                                                    title: 'Quyền sỡ hữu của người nước ngoài'
                                                },
                                                {
                                                    title: 'Mua bán - đã thế chấp'
                                                }
                                            ],
                                            displayed: false,
                                            docked: 'top',
                                            draggable: false,
                                            hideOnMaskTap: false,
                                            margin: '',
                                            padding: 10,
                                            inline: false,
                                            itemTpl: [
                                                '<div class="title-ht">{title}</div><div class="icon-ht"><i class="fa fa-angle-right btn-ht"></i></div>'
                                            ],
                                            grouped: true,
                                            rowLines: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container'
                                },
                                {
                                    xtype: 'container',
                                    docked: 'top',
                                    margin: '20 0 0 0',
                                    layout: 'center',
                                    items: [
                                        {
                                            xtype: 'button',
                                            cls: 'btn',
                                            style: 'text-transform :none;',
                                            ui: 'dangnhap',
                                            width: 179,
                                            text: 'Gửi câu hỏi của bạn'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '8%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'title-container',
                                    height: '10%',
                                    html: 'Đặc quyền',
                                    margin: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: '92%'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '12%',
            style: 'background-color: #2a8daf;',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-home',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Trang chủ'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-file',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Tin tức'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-star',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Sự kiện'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-gift',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Đặc quyền'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-credit-card',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Thanh toán'
                        }
                    ]
                }
            ]
        }
    ]

});