/*
 * File: app/view/tai_khoan.js
 * Date: Tue Mar 20 2018 08:57:59 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.tai_khoan', {
    extend: 'Ext.Container',
    alias: 'widget.tai_khoan',

    requires: [
        'LoginApp.view.LoginPanelViewModel13',
        'Ext.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.Label',
        'Ext.Img'
    ],

    viewModel: {
        type: 'tai_khoan'
    },
    disabled: true,
    height: '100%',
    data: {
        title: 'Ưu đãi giảm giá 20% tại Le Mendendline'
    },
    displayed: true,
    padding: '',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '8%',
            width: '100%',
            centered: true,
            docked: 'top',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    width: '33%',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 40,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-long-arrow-left',
                                    text: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    style: 'background: url(images/logo.png);background-repeat: no-repeat;background-position: center;background-size:cover;background-size: 80%',
                    width: '33%',
                    html: '',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    width: '33%',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            width: '40%'
                        },
                        {
                            xtype: 'container',
                            width: '60%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 40,
                                    style: 'border-radius: 50%;',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    arrow: false,
                                    icon: 'true',
                                    iconCls: 'x-fa fa-user-circle',
                                    text: '',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-user',
                                                text: 'Tài khoản'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-qrcode',
                                                text: 'QR Code'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-question-circle-o',
                                                text: 'Hỗ trợ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-cog',
                                                text: 'Cài đặt'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-headphones',
                                                text: 'Liên hệ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: 'true',
                                                iconCls: 'x-fa fa-sign-out',
                                                text: 'Đăng xuất'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '88%',
            layout: 'card',
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'container',
                            height: '8%',
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'title-container',
                                    height: '10%',
                                    html: 'Cập nhật tài khoản',
                                    margin: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 144,
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'container',
                                    height: '85%',
                                    width: 130,
                                    layout: 'center',
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: '85%',
                                            width: '100%',
                                            src: 'images/qrcode.png'
                                        },
                                        {
                                            xtype: 'container',
                                            height: 46,
                                            style: 'text-align:center;',
                                            docked: 'bottom',
                                            margin: '-10 0 0 0',
                                            layout: 'center',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    height: 40,
                                                    style: 'background:#ddd;',
                                                    ui: 'user-menu-button',
                                                    width: 40,
                                                    docked: 'right',
                                                    zIndex: 99999,
                                                    icon: 'true',
                                                    iconCls: 'x-fa fa-pencil-square-o'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: '15%',
                                    style: 'text-align:center;',
                                    docked: 'bottom',
                                    margin: '-10 0 0 0',
                                    layout: 'center',
                                    items: [
                                        {
                                            xtype: 'label',
                                            cls: 'content-container',
                                            height: 31,
                                            docked: 'top',
                                            html: 'Tiếng Việt'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 40,
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            padding: '0 0 0 20',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'content-container',
                                    height: '10%',
                                    html: 'Đổi mật khẩu',
                                    margin: '10 0 0 0'
                                },
                                {
                                    xtype: 'button',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    docked: 'right',
                                    margin: '0 20 0 0',
                                    icon: 'true',
                                    iconCls: 'x-fa fa-pencil'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 40,
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            padding: '0 20 0 20',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'content-container',
                                    html: 'Thông báo',
                                    margin: '10 0 0 0'
                                },
                                {
                                    xtype: 'button',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    docked: 'right',
                                    margin: '0 20 0 0',
                                    icon: 'true',
                                    iconCls: 'x-fa fa-pencil'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 40,
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            padding: '0 0 0 20',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'content-container',
                                    height: '10%',
                                    html: 'Khác',
                                    margin: '10 0 0 0'
                                },
                                {
                                    xtype: 'button',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    docked: 'right',
                                    margin: '0 20 0 0',
                                    icon: 'true',
                                    iconCls: 'x-fa fa-pencil'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 40,
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            padding: '0 0 0 20',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'content-container',
                                    html: 'Thông báo',
                                    margin: '10 0 0 0'
                                },
                                {
                                    xtype: 'button',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    docked: 'right',
                                    margin: '0 20 0 0',
                                    icon: 'true',
                                    iconCls: 'x-fa fa-pencil'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 40,
                            style: 'border-bottom:1px solid #b8cfff;',
                            docked: 'top',
                            padding: '0 0 0 20',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'content-container',
                                    height: '10%',
                                    html: '093 747 3880',
                                    margin: '10 0 0 0'
                                },
                                {
                                    xtype: 'button',
                                    ui: 'user-menu-button',
                                    width: 40,
                                    docked: 'right',
                                    margin: '0 20 0 0',
                                    icon: 'true',
                                    iconCls: 'x-fa fa-pencil'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: '12%',
            style: 'background-color: #2a8daf;',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-home',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Trang chủ'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-file',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Tin tức'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-star',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Sự kiện'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-gift',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Đặc quyền'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    width: '50%',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            style: 'border-radius: 50%;',
                            ui: 'tab-panel-menu',
                            width: 40,
                            icon: 'true',
                            iconCls: 'x-fa fa-credit-card',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            cls: 'tab-panel-menu',
                            html: 'Thanh toán'
                        }
                    ]
                }
            ]
        }
    ]

});