/*
 * File: app/view/TaskItem.js
 * Date: Mon Mar 19 2018 10:14:04 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.TaskItem', {
    extend: 'Ext.Container',
    alias: 'widget.taskitem',

    requires: [
        'LoginApp.view.TaskItemViewModel',
        'Ext.Container'
    ],

    viewModel: {
        type: 'taskitem'
    },
    userCls: 'tvc-tsk-item',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    height: 40,
                    width: 40,
                    padding: 5,
                    bind: {
                        userCls: 'tvc-tsk-ico {recType}'
                    }
                },
                {
                    xtype: 'component',
                    flex: 1,
                    userCls: 'tvc-tsk-title',
                    margin: '0 0 10 0',
                    bind: {
                        html: '{titleType}'
                    }
                },
                {
                    xtype: 'component',
                    height: 10,
                    width: 10,
                    margin: '11 0',
                    bind: {
                        userCls: 'tvc-tsk-status-{read}'
                    }
                }
            ]
        },
        {
            xtype: 'component',
            userCls: 'tvc-tsk-content',
            maxHeight: 120,
            padding: '0 0 0 40',
            bind: {
                html: '{shortDesc}'
            }
        }
    ],

    updateRecord: function(record, eOpts) {
        var me	=this,
            host= Ext.domainHost;

        if (host === undefined) host = '';
        me.callParent(arguments);
        if(record) {
            me.getViewModel().setData(record.getData());

        //     if (record.get('attachCount') > 0 ) {
        //         FrmFdDocument.getLink({
        //             linkto: 'WLT',
        //             referencekey1: record.get('recordid'),
        //             referencekey2: record.get('linenum')
        //         },function(resLink) {
        //             if (resLink && resLink.success) {
        //                 if(resLink.data.length > 0) {
        //                     var img = resLink.data[0],
        //                         url	= '';

        //                     me.down('#imgCmt').setHidden(false);
        //                     url = Ext.isChrome ? '/proxy/' + encodeURIComponent(host+'/frmfddocument/getfile?id=') + img.documentcode : (host+'/frmfddocument/getfile?id=' + img.documentcode);
        //                     me.down('#imgCmt').setSrc(url);
        //                 } else {
        //                     me.down('#imgCmt').setHidden(true);
        //                 }
        //             }
        //         });
        //     } else me.down('#imgCmt').setHidden(true);
        }
    }

});