/*
 * File: app/view/TaskItemViewModel.js
 * Date: Mon Mar 19 2018 10:14:04 GMT+0700 (SE Asia Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.TaskItemViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.taskitem',

    requires: [
        'Ext.app.bind.Formula'
    ],

    formulas: {
        titleType: function(get) {
            return get('title');
        },
        recType: function(get) {
            var t = get('recordtype');
            if (t == 'A') return 'x-fa fa-newspaper-o';
            if (t == 'B') return 'x-fa fa-bullhorn';
            if (t == 'I') return 'x-fa fa-comment';
            return '';
        },
        shortDesc: function(get) {
            return Ext.util.Format.nl2br(get('description'));
        }
    }

});