/*
 * File: app/view/Test.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmpriteCity.view.Test', {
    extend: 'Ext.Container',
    alias: 'widget.test',

    requires: [
        'EmpriteCity.view.TestViewModel',
        'Ext.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'test'
    },
    layout: 'center',

    items: [
        {
            xtype: 'button',
            enableToggle: true,
            text: 'MyButton2',
            menu: {
                xtype: 'menu',
                width: 120,
                activeChildTabIndex: 1,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    }
                ]
            }
        }
    ]

});