/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    views: [
        'Main',
        'hung0',
        'hung1',
        'hung2',
        'hung4',
        'hung5',
        'hung6',
        'hung7',
        'hung8',
        'hung9',
        'hung10',
        'hung11',
        'hung12',
        'hung13',
        'hung3',
        'hung',
        'MyContainer5',
        'MyContainer4',
        'MyContainer8'
    ],
    name: 'adc',

    launch: function() {
        Ext.create('adc.view.Main', {fullscreen: true});
    }

});
