/* auto generated by architect */ 
Ext.theme.addManifest([
    {
        "ui": "tab-panel-menu",
        "xtype": "button"
    },
    {
        "ui": "menu-button",
        "xtype": "button"
    },
    {
        "ui": "user-menu-button",
        "xtype": "button"
    }
]);